export const GET_ALL_COUNTRIES = 'GET_ALL_COUNTRIES';
export const INIT_HOME = 'INIT_HOME';
export const GET_COUNTRY_BY_ID = 'GET_COUNTRY_BY_ID';
export const GET_COUNTRIES_BY_NAME = 'GET_COUNTRIES_BY_NAME';
export const SET_PAGE = 'SET_PAGE';
export const COUNTRIES_CURENT_PAGE = 'COUNTRIES_CURENT_PAGE';
export const FILTER_BY_CONTINENT = 'FILTER_BY_CONTINENT';
export const SET_ORDER = 'SET_ORDER';
